default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  post: 5432

development:
  <<: *default
  host: localhost
  database: bright_dictionary
  username: vensera
  password: 

test:
  <<: *default
  host: localhost
  database: bright_dictionary_test
  username: vensera
  password: 


staging:
  <<: *default
  host: localhost
  database: bright_dictionary_stg
  username: vensera
  password: 

production:
  <<: *default
  host: ec2-23-21-162-90.compute-1.amazonaws.com
  database: d72395nptis18d
  username: vkaxhyntmnmycd
  password: bee8a07a52c06f503c381be0e0bf18ee46a4aa31588411fc5285f46de0a4034c
